--DROP TABLE "MEMBER" CASCADE CONSTRAINTS;

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PROFILE_IMG"	VARCHAR2(4000)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_OPEN_FL"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"SECESSION_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일(아이디로 사용, 중복x)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호(암호화 진행)';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임(중복X)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PROFILE_IMG" IS '회원 프로필 이미지 경로';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_OPEN_FL" IS '계정공개여부(Y:공개, N:비공개)';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '계정탈퇴여부(Y:탈퇴, N:탈퇴X)';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '회원 권한(1: 일반, 2: 관리자)';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_PUB_PRI_FL"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"COMMENT_BLOCK_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_CREATE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부';

COMMENT ON COLUMN "BOARD"."BOARD_PUB_PRI_FL" IS '게시글 좋아요 / 조회수 공개여부';

COMMENT ON COLUMN "BOARD"."COMMENT_BLOCK_FL" IS '댓글 차단 여부';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '게시글 작성 회원 번호';

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_ORDER"	NUMBER		NOT NULL,
	"IMG_ADDRESS"	VARCHAR2(300)		NOT NULL,
	"IMG_ACCESSIBILITY"	VARCHAR2(500)		NULL,
	"IMG_ORIGINAL_NAME"	VARCHAR2(500)		NOT NULL,
	"IMG_CHANGE_NAME"	VARCHAR2(500)		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지 번호(SEQ_IMG_NO)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '이미지 파일 순서 번호';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ADDRESS" IS '이미지 저장 폴더 경로';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ACCESSIBILITY" IS '접근성(장애인)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIGINAL_NAME" IS '원본 이미지 파일 이름';

COMMENT ON COLUMN "BOARD_IMG"."IMG_CHANGE_NAME" IS '변경된 이미지 파일 이름';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '이미지가 첨부된 게시글 번호';

CREATE TABLE "FOLLOW" (
	"F_FROM_MEMBER_NO"	NUMBER		NOT NULL,
	"F_T0_TARGET_NO"	NUMBER		NULL,
	"FOLLOW_TYPE"	CHAR(1)		NOT NULL,
	"FOLLOW_ACCEPT_FL"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "FOLLOW"."F_FROM_MEMBER_NO" IS '팔로우 한 회원번호';

COMMENT ON COLUMN "FOLLOW"."F_T0_TARGET_NO" IS '팔로우 당한 회원번호';

COMMENT ON COLUMN "FOLLOW"."FOLLOW_TYPE" IS '팔로우 대상 타입(M:회원, H:해시태그)';

COMMENT ON COLUMN "FOLLOW"."FOLLOW_ACCEPT_FL" IS '팔로우 승인 여부(Y:팔로우 승인, N:팔로우 거절)';

DROP TABLE "REPORT";

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_TARGET_NO"	NUMBER		NULL,
	"REPORT_TYPE"	VARCHAR2(3)		NULL,
	"REPORT_REASON"	VARCHAR2(20)		NULL,
	"REPORT_CONTENT"	VARCHAR2(4000)		NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고 번호(SEQ_NOTIFY_NO)';

COMMENT ON COLUMN "REPORT"."REPORT_TARGET_NO" IS '신고할 대상 번호';

COMMENT ON COLUMN "REPORT"."REPORT_TYPE" IS '신고대상(글,회원)';

COMMENT ON COLUMN "REPORT"."REPORT_REASON" IS '신고 사유 번호 선택';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고할 내용';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고한 일자';

CREATE TABLE "BOARD_LIKE" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '좋아요 한 게시글 번호';

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '좋아요 한 회원 번호';

CREATE TABLE "BOOKMARK" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOOKMARK"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOOKMARK"."MEMBER_NO" IS '북마크 한 회원번호';

CREATE TABLE "CHAT" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"CHAT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CHAT_SEND_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_READ_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"CHATTING_NO"	NUMBER		NOT NULL,
	"C_FROM_MEMBER_NO"	NUMBER		NOT NULL,
	"C_TO_MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHAT"."CHAT_NO" IS '채팅 번호(SEQ_CHAT_NO)';

COMMENT ON COLUMN "CHAT"."CHAT_CONTENT" IS '채팅 내용';

COMMENT ON COLUMN "CHAT"."CHAT_SEND_DATE" IS '채팅 발송 시간';

COMMENT ON COLUMN "CHAT"."CHAT_READ_FL" IS '채팅 확인 여부';

COMMENT ON COLUMN "CHAT"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHAT"."C_FROM_MEMBER_NO" IS '채팅 보낸 회원';

COMMENT ON COLUMN "CHAT"."C_TO_MEMBER_NO" IS '채팅 받는 회원';

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"COMMENT_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"UPPER_COMMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호(SEQ_COMMENT_NO)';

COMMENT ON COLUMN "COMMENT"."COMMENT_MEMBER_NO" IS '댓글 작성 회원 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '게시글 댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_CREATE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "COMMENT"."UPPER_COMMENT_NO" IS '상위 댓글 번호';

CREATE TABLE "COMMENT_LIKE" (
	"LIKE_COMMENT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT_LIKE"."LIKE_COMMENT_NO" IS '좋아요한 댓글 번호';

COMMENT ON COLUMN "COMMENT_LIKE"."MEMBER_NO" IS '좋아요 한 회원 번호';

CREATE TABLE "HASHTAG" (
	"HASHTAG_NO"	NUMBER		NOT NULL,
	"HASHTAG_CONTENT"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "HASHTAG"."HASHTAG_NO" IS '해시태그 번호(SEQ_HASHTAG_NO)';

COMMENT ON COLUMN "HASHTAG"."HASHTAG_CONTENT" IS '해시태그 내용';

CREATE TABLE "BLOCK" (
	"B_FROM_MEMBER_NO"	NUMBER		NOT NULL,
	"B_TO_MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BLOCK"."B_FROM_MEMBER_NO" IS '차단한 회원 번호';

COMMENT ON COLUMN "BLOCK"."B_TO_MEMBER_NO" IS '차단 당한 회원번호';

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"NOTICE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '알림 번호(SEQ_NOTICE_NO)';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '알림 내용(팔로우, 댓글, 언급 등)';

COMMENT ON COLUMN "NOTICE"."NOTICE_DATE" IS '알림 시간';

COMMENT ON COLUMN "NOTICE"."MEMBER_NO" IS '회원번호';

CREATE TABLE "CHATTING_ROOM" (
	"CHATTING_NO"	NUMBER		NOT NULL,
	"CHATTING_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO_1"	NUMBER		NOT NULL,
	"MEMBER_NO_2"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_NO" IS '채팅방 번호(SEQ_CHAT_ROOM_NO)';

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_CREATE_DATE" IS '채팅방 생성일';

COMMENT ON COLUMN "CHATTING_ROOM"."MEMBER_NO_1" IS '채팅방 회원 1';

COMMENT ON COLUMN "CHATTING_ROOM"."MEMBER_NO_2" IS '채팅방 회원 2';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_EMAIL"UNIQUE (
	"MEMBER_EMAIL"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER"UNIQUE (
	"MEMBER_NICKNAME"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (
	"F_FROM_MEMBER_NO",
	"F_T0_TARGET_NO",
	"FOLLOW_TYPE"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_NO"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "PK_BOOKMARK" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "PK_COMMENT_LIKE" PRIMARY KEY (
	"LIKE_COMMENT_NO",
	"MEMBER_NO"
);

ALTER TABLE "HASHTAG" ADD CONSTRAINT "PK_HASHTAG" PRIMARY KEY (
	"HASHTAG_NO"
);

ALTER TABLE "BLOCK" ADD CONSTRAINT "PK_BLOCK" PRIMARY KEY (
	"B_FROM_MEMBER_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "PK_CHATTING_ROOM" PRIMARY KEY (
	"CHATTING_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW_1" FOREIGN KEY (
	"F_FROM_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_BOARD_TO_BOOKMARK_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_MEMBER_TO_BOOKMARK_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "FK_CHATTING_ROOM_TO_CHAT_1" FOREIGN KEY (
	"CHATTING_NO"
)
REFERENCES "CHATTING_ROOM" (
	"CHATTING_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_1" FOREIGN KEY (
	"C_FROM_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_2" FOREIGN KEY (
	"C_TO_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"LIKE_COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"LIKE_COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BLOCK" ADD CONSTRAINT "FK_MEMBER_TO_BLOCK_1" FOREIGN KEY (
	"B_FROM_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_ROOM_1" FOREIGN KEY (
	"MEMBER_NO_1"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_ROOM_2" FOREIGN KEY (
	"MEMBER_NO_2"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

