-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO; -- 회원 번호
CREATE SEQUENCE SEQ_BOARD_NO; -- 게시글 번호
CREATE SEQUENCE SEQ_COMMENT_NO; -- 댓글 번호
CREATE SEQUENCE SEQ_IMG_NO; -- 게시글 이미지 번호
CREATE SEQUENCE SEQ_HASHTAG_NO; -- 해시태그 번호
CREATE SEQUENCE SEQ_CHAT_NO; -- 채팅 번호
CREATE SEQUENCE SEQ_CHAT_ROOM_NO; -- 채팅방 번호
CREATE SEQUENCE SEQ_NOTICE_NO; -- 알림 번호
CREATE SEQUENCE SEQ_REPORT_NO; -- 신고 번호

-- 회원 샘플 데이터 생성
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01@naver.com', 'pass01!',
'유저일', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT );

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02@naver.com', 'pass02!',
'유저이', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT );

INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user03@naver.com', 'pass03!', '유저삼', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user04@naver.com', 'pass04!', '유저사', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user05@naver.com', 'pass05!', '유저오', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user06@naver.com', 'pass06!', '유저육', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user07@naver.com', 'pass07!', '유저칠', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user08@naver.com', 'pass08!', '유저팔', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user09@naver.com', 'pass09!', '유저구', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user10@naver.com', 'pass10!', '유저십', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);


-- 게시글 샘플 데이터 생성

INSERT INTO BOARD 
VALUES(SEQ_BOARD_NO.NEXTVAL, '게시글 샘플 내용, 안녕하세요 반갑습니다~~~', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 5 );

INSERT INTO BOARD 
VALUES(SEQ_BOARD_NO.NEXTVAL, '유저육의 게시글입니다, 샘플 데이터 내용입니다~~~', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 6 );

INSERT INTO "BOARD"
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 이에요, 완벽한 우리팀', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 7);

INSERT INTO "BOARD"
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 두번째 입니다, 화이팅입니다. 우리팀', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 8);

INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, '월요일', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 9);

INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, '11시 47분', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 10);

INSERT INTO "BOARD"
VALUES (SEQ_BOARD_NO.NEXTVAL, '데이터베이스를 만들고 있다. 오늘 시험도 봤다. 집에 가고 싶다..', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '3');

INSERT INTO "BOARD"
VALUES (SEQ_BOARD_NO.NEXTVAL, '유저사의 게시글입니다. 길게 작성해보겠습니다. 동해물과 백두산이 마르고 닳도록 하느님이 보우하사 우리나라만세. 무궁화 삼천리 화려강산 대한사람 대한으로 길이 보전하세.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '4');

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '유저일 샘플데이터 내용 작성중입니다.', DEFAULT,
DEFAULT, DEFAULT, DEFAULT,1);

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '유저이 샘플데이터 내용 작성중입니다.', DEFAULT,
DEFAULT, DEFAULT, DEFAULT,2);


-- 댓글 샘플 데이터 생성
INSERT INTO "COMMENT" 
VALUES(SEQ_COMMENT_NO.NEXTVAL, 5, '월요일은 월요병', DEFAULT, 5, NULL); -- 환재

INSERT INTO "COMMENT" 
VALUES(SEQ_COMMENT_NO.NEXTVAL, 6, '우리팀 최고! 우리 팀원들도 최고!', DEFAULT, 4, NULL); -- 아민

INSERT INTO "COMMENT" 
VALUES(SEQ_COMMENT_NO.NEXTVAL, 5, '저도 집에 가고싶어요...', DEFAULT, 7, NULL); -- 은지언니

INSERT INTO "COMMENT" 
VALUES(SEQ_COMMENT_NO.NEXTVAL, 6, '주영이 빠따 한 대 추가', DEFAULT, 10, NULL); -- 주영이

INSERT INTO "COMMENT" 
VALUES(SEQ_COMMENT_NO.NEXTVAL, 6, '나도 짜증나', DEFAULT, 5, 16); -- 너무 짜증나

INSERT INTO "COMMENT" 
VALUES(SEQ_COMMENT_NO.NEXTVAL, 6, '미쳤나?', DEFAULT, 5, 25); -- 너무 짜증나


-- 게시글 SELECT문 작성

-- 전체 게시글 조회
SELECT MEMBER_NO, MEMBER_NICKNAME, BOARD_NO, BOARD_CONTENT, BOARD_CREATE_DATE,
BOARD_PUB_PRI_FL, COMMENT_BLOCK_FL
FROM "MEMBER"
JOIN "BOARD" USING(MEMBER_NO)
WHERE SECESSION_FL = 'N'
AND BOARD_DEL_FL = 'N'
ORDER BY BOARD_CREATE_DATE DESC;

SELECT BOARD_NO, COUNT(COMMENT_NO)
FROM "MEMBER"
JOIN "BOARD" USING(MEMBER_NO)
JOIN "COMMENT" USING(BOARD_NO)
WHERE BOARD_DEL_FL = 'N'
GROUP BY BOARD_NO;

SELECT COMMENT_NO, COMMENT_MEMBER_NO, COMMENT_CONTENT , COMMENT_CREATE_DATE, UPPER_COMMENT_NO, BOARD_NO
FROM "COMMENT"
ORDER BY BOARD_NO DESC;


-- 내 게시글 조회
SELECT MEMBER_NO, MEMBER_NICKNAME, BOARD_NO, BOARD_CONTENT, BOARD_CREATE_DATE,
BOARD_PUB_PRI_FL, COMMENT_BLOCK_FL
FROM "MEMBER"
JOIN "BOARD" USING(MEMBER_NO)
WHERE SECESSION_FL = 'N'
AND BOARD_DEL_FL = 'N'
AND MEMBER_NO = 5
ORDER BY BOARD_CREATE_DATE DESC;
--에서 보드 넘버 얻어 와서

SELECT BOARD_NO, COUNT(COMMENT_NO)
FROM "MEMBER"
JOIN "BOARD" USING(MEMBER_NO)
JOIN "COMMENT" USING(BOARD_NO)
WHERE BOARD_DEL_FL = 'N'
AND MEMBER_NO = 5
GROUP BY BOARD_NO;
-- 댓글 몇개인지 표시하고

SELECT COMMENT_NO, COMMENT_MEMBER_NO, COMMENT_CONTENT , COMMENT_CREATE_DATE, UPPER_COMMENT_NO, BOARD_NO
FROM "COMMENT"
WHERE BOARD_NO = 1
ORDER BY COMMENT_CREATE_DATE;
-- 보드 넘버로 댓글 전체 조회


-- ~~을 포함한 게시글 조회

SELECT MEMBER_NO, MEMBER_NICKNAME, BOARD_NO, BOARD_CONTENT, BOARD_CREATE_DATE,
BOARD_PUB_PRI_FL, COMMENT_BLOCK_FL
FROM "MEMBER"
JOIN "BOARD" USING(MEMBER_NO)
WHERE SECESSION_FL = 'N'
AND BOARD_DEL_FL = 'N'
AND BOARD_CONTENT LIKE '%샘플%'
ORDER BY BOARD_CREATE_DATE DESC;
-- 본문에 샘플이라는 단어를 포함하고 있는 게시글 조회


